testv1:
	go test v1/sum_test.go v1/sum.go -v -race
.PHONY: testv1

testv2:
	go test v2/sum_test.go v2/sum.go -v -race
.PHONY: testv2

testcoverv2:
	go test v2/sum_test.go v2/sum.go -cover -v -race
.PHONY: testcoverv2

testv3:
	go test v3/sum_test.go v3/sum.go -v -race
.PHONY: testv3

testv4:
	go test v4/sum_test.go v4/sum.go -v -race
.PHONY: testv4
