testv1:
	go test v1/context_test.go v1/context.go -v -race
.PHONY: testv1

testv2:
	go test v2/context_test.go v2/context.go -v -race
.PHONY: testv2

testx:
	go test exp/context_test.go exp/context.go -v -race
.PHONY: testx