testv1:
	go test v1/main_test.go v1/main.go -v -race
.PHONY: testv1

testv2:
	go test v2/main_test.go v2/main.go -v -race
.PHONY: testv2

testv3:
	go test v3/main_test.go v3/main.go -v -race
.PHONY: testv3

 