
# v0 is a copy from previous section's latest version v9
testv0:	
	# sorting - players sorted by their scores, from highest to lowest
	go test v0/*.go  -v -race
.PHONY: testv0

testv1:	
	go test v1/*.go  -v -race
.PHONY: testv1