testv1:
	go test v1/reflection_test.go v1/reflection.go -v -race
.PHONY: testv1

testv2:
	go test v2/reflection_test.go v2/reflection.go -v -race
.PHONY: testv2

testv3:
	go test v3/reflection_test.go v3/reflection.go -v -race
.PHONY: testv3

testv4:
	go test v4/reflection_test.go v4/reflection.go -v -race
.PHONY: testv4

testv5:
	go test v5/reflection_test.go v5/reflection.go -v -race
.PHONY: testv5

testv6:
	go test v6/reflection_test.go v6/reflection.go -v -race
.PHONY: testv6

testv7:
	go test v7/reflection_test.go v7/reflection.go -v -race
.PHONY: testv7

testv8:
	go test v8/reflection_test.go v8/reflection.go -v -race
.PHONY: testv8

testv9:
	go test v9/reflection_test.go v9/reflection.go -v -race
.PHONY: testv9

testv91:
	go test v9.1/reflection_test.go v9.1/reflection.go -v -race
.PHONY: testv91

testv10:
	go test v10/reflection_test.go v10/reflection.go -v -race
.PHONY: testv10

testv11:
	go test v11/reflection_test.go v11/reflection.go -v -race
.PHONY: testv11
